name: MyWorkFlow
on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Welcome Message
          run: echo 'Welcome Message'
        - name: list of files
          run: ls  
        - name: dispaly file
          run: cat README.md